apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librespeed-config-pvc
  namespace: librespeed
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi