apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data-pvc
  namespace: uptime-kuma
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi